version: '3.0'


services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-storage:/data
    networks:
      - es-network

volumes:
  minio-storage:
    driver: local

networks:
  es-network:
